#pragma once
#pragma comment(lib,"dll/glfw3.lib")
#pragma comment(lib,"dll/glfw3dll.lib")
#pragma comment(lib,"dll/glew32.lib")
//#pragma comment(lib,"dll/glew32s.lib")
#pragma comment(lib,"opengl32.dll")
// GLEW
#define GLEW_STATIC
#include <GL/glew.h>
// GLFW
#include <GLFW/glfw3.h>